### ISSUE TITLE
Xgterm not opening

### ISSUE THREAD

**Issue by zoispetsieri** [iraf-community/x11iraf#24]
Hello,
I installed iraf and x11iraf on my ubuntu 20.04 machine. However when I try to open xgterm I get:

Command 'xgterm' not found, did you mean:

  command 'xterm' from deb xterm (353-1ubuntu1)

Try: sudo apt install <deb name>

Do you have any solution to this isssue?

**Comment by olebole** [comment]
How exactly did you install it?

**Comment by zoispetsieri** [comment]
I first installed iraf following the instructions on:
https://iraf-community.github.io/install.html
and I had no problem with the installation.
I then moved on to install x11iraf based on the instructions given on:  
https://iraf-community.github.io/x11iraf
but for some reason the binaries of x11iraf could not be installed.
The message I get is  "Installing new binaries in /usr/local/bin ...foreach: No match."

**Comment by olebole** [comment]
Ar you sure that you installed the latest version (2.0+2020.06.15)?
BTW, in Ubuntu, you can install IRAF directly with `sudo apt install iraf`.

**Comment by zoispetsieri** [comment]
My very first attempt was using sudo apt install iraf but xgterm didn't
work. So I tried the source installation. Unfortunately I did not install
the latest version. I installed iraf-2.16.1-2018.11.01  I'll try the new
version.
Thank you so much for your help

**Comment by olebole** [comment]
x11iraf is not part of Iraf, but a separate package (and not included in Ubuntu yet). So, you can still use the Ubuntu package for Iraf and compile only x11iraf yourself.
