### ISSUE TITLE
Error with tcl header file 

### ISSUE THREAD

**Issue by JiahuiZhuo** [iraf-community/x11iraf#31]
The code expect  `tcl.h` to be in `/usr/include/tcl/` but Arch places `tcl.h` in `/usr/include/`

Maybe I should try making a symbolic link to tcl.h, not sure if that would work.

![shot1](https://user-images.githubusercontent.com/30496480/94966053-e7abd580-04fc-11eb-9248-25ddbf26af29.png)

![shot2](https://user-images.githubusercontent.com/30496480/94967156-d237ab00-04fe-11eb-86fe-62f5284cafb0.png)

**Comment by JiahuiZhuo** [comment]
Changing "tcl/tcl.h" to "tcl.h" at following files make the code work correctly:
./obm/ObmP.h
./ximtool/ximclient.c
./ximtool/ism.c
./ximtool/ism_wcspix.c

**Comment by JiahuiZhuo** [comment]
I did a Arch packages to install x11iraf from github but on Arch way, I mean following Arch package guidelines.
[Link](https://aur.archlinux.org/packages/x11iraf/)
But I think that modified the source code and add the Arch Support wouldn't be something difficult. I don't know, maybe something like detect firstly if exist `tcl/tcl.h` and `tcl.h`, if exist only `tcl.h` then change the path of `tcl.h` correctly.
![x11irafpass](https://user-images.githubusercontent.com/30496480/95639013-1135a580-0a97-11eb-9064-c3a612a08c88.png)

**Comment by olebole** [comment]
Closed by #32.
