### ISSUE TITLE
xgterm sets the wrong TERM variable

### ISSUE THREAD

**Issue by olebole** [iraf-community/x11iraf#4]
Copied from [iraf/iraf-v216#120](https://iraf-community.github.io/iraf-v216/issues/120):

When starting xgterm, the `TERM` variable has the wrong value:
```
$ echo $TERM
vt100
```
The reason is that xgterm tries to get the value from the `terminfo` database, which does not contain an entry for `xgterm`, and then falls back to `vt100`.

An way to install xgterm in the database is to call the `tic` terminfo compiler with the following file as argument (tic is part of the ncurses binaries):
```
# xgterm.terminfo: Terminfo entry source for xgterm
# compile with "tic xgterm.terminfo"
xgterm|graphic terminal for IRAF,
	use=xterm-r5,
```
This will compile and install a database entry in the home directory (resp. in the standard terminfo dir, when compiled as root) and so allows xgterm to set the correct `TERM` variable.
```
$ echo $TERM
xgterm
```
This should be part of the IRAF installation procedure.

**Comment by horbrastar** [comment]
I have the same problem with a new install of IRAF, though the $TERM value I find is xterm-256color.  Where is the "standard terminfo directory".

**Comment by olebole** [comment]
That depends on your system. `/usr/share/terminfo/` on Debian, and probably on other Linux systems.

**Comment by horbrastar** [comment]
Thanks.  I'm on UBUNTU 20.04, and I do see a folder /usr/share/terminfo/.
