### ISSUE TITLE
compiling x11iraf on fedora

### ISSUE THREAD

**Issue by prajwel** [iraf-community/x11iraf#42]
Hi, 

   I replaced my existing IRAF installation with the community edition (OS: Fedora 34). There were some problems, but I managed to compile x11iraf. These were the steps I followed.

`sudo dnf install ncurses-devel tcl-devel libXaw-devel Xaw3d-devel flex-devel bison-devel byacc`

(I think the other packages should already be present in the OS). 

For the following files, change the line `#include <tcl/tcl.h>` to `#include <tcl.h>`

```
obm/ObmP.h  
ximtool/ism.c 
ximtool/ism_wcspix.c
ximtool/ximclient.c
```

I don't know how to best submit this as a pull request. Should it be added to the documentation? I am sorry if this has been already mentioned somewhere, I could not find it when I tried.

**Comment by olebole** [comment]
This is already fixed in #32; we just didn't release a new version yet.
