### ISSUE TITLE
'X11/Intrinsic.h' file not found

### ISSUE THREAD

**Issue by pmassey** [iraf-community/x11iraf#54]
I'm installing X11IRAF on an intel iMac recently upgraded to Ventura.   However, when I go to do the "make" for X11IRAF, I get the following error: 
```
bash-3.2$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C obm
cc -I/usr/include/tcl -I/usr/X11/include   -c -o Obm.o Obm.c
In file included from Obm.c:5:
./ObmP.h:16:10: fatal error: 'X11/Intrinsic.h' file not found
#include <X11/Intrinsic.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [Obm.o] Error 1
make: *** [obm/libobm.a] Error 2
```

**Comment by olebole** [comment]
I think you need a recent XQuartz; at least this was the problem [here](https://github.com/orgs/iraf-community/discussions/258).

**Comment by olebole** [comment]
This is only needed if you want to use the **ximtool** program and have it WCS coordinates displayed. In this case, you would also need an installed IRAF, and **mkpkg** in the `PATH`.
Just for **xgterm** this is not needed, as you said.
