### ISSUE TITLE
x11iraf/xgterm compilation problem 

### ISSUE THREAD

**Issue by amnferguson** [iraf-community/x11iraf#55]
Hi there - I've successfully installed iraf but not x11iraf on an iMac (2017) running Ventura 13.6 with latest code. I'm attaching the build.log with the error that appears at the end. Unfortunately I have no idea what it means! Many thanks.

[build.log](https://github.com/iraf-community/x11iraf/files/12735923/build.log)

**Comment by olebole** [comment]
See [discussion#261](https://github.com/orgs/iraf-community/discussions/261) resp. [discussion#228](https://github.com/orgs/iraf-community/discussions/228) resp. #46.

**Comment by amnferguson** [comment]
Thank you (and apologies for not spotting the explanation elsewhere)! x11iraf compiled fine but on opening xgterm, I get the same warning message as reported at the end of this post
 https://github.com/iraf-community/x11iraf/issues/33#issuecomment-739246588
..namely 

> Warning: no access to tty (Undefined error: 0).
> Thus no job control in this shell.

I realise this isn't critical but if there was ever a fix could you point me to it? Thanks again.
