### ISSUE TITLE
problems with installing x11iraf-2.1

### ISSUE THREAD

**Issue by crabcakies231** [iraf-community/x11iraf#56]
I have tried to install lastest x11iraf on Ubuntu 22.04.03LTS, aka jammy.  i have followed the instructions given here:  https://iraf-community.github.io/x11iraf, and checked what i have done several times.
while the x11 programs were compiled and can be run outside of the iraf environment, there appears to be no link to actions within iraf . thus, if I do  an implot dev$pix action within an xgterm,  the error msg appears stating that terminal does not support vector graphics.  same response for ximtool.

in the past i have had no problems installing x11iraf on my linux running ubuntu 21. thus, i am at a loss as to how to overcome this problem.

not sure if this is useful, but here is a screenshot of trying implot $dev$pix within xgterm
![Screenshot from 2023-11-07 08-13-23](https://github.com/iraf-community/x11iraf/assets/148261308/af4598bb-efa1-407e-9837-f001064d7f4e)

**Comment by olebole** [comment]
You need to start IRAF within xgterm to get it running.
And, on Ubuntu 22.04, you don't need to compile xgterm by itself; just doing **sudo apt install xgtern** also does the trick.

**Comment by crabcakies231** [comment]
danke. aber das Problem bleibt.  Siehe Anhang

**Comment by olebole** [comment]
I am quite sure that this is the problem. The screenshot shows that in the xgterm you still are using the shell, i.e. you didn't start IRAF. Without starting IRAF, it will not work.

**Comment by crabcakies231** [comment]
in this screen shot iraf is running within the xgterm and the original
problem still exists and graphics does NOT work

**Comment by crabcakies231** [comment]
i am referring to the original problem, not my stupid action regarding the
cl not operating

**Comment by olebole** [comment]
On Giithub, you  can't add an attachment via mail; it is not visible. Please go to the issue web page and insert it there.

**Comment by olebole** [comment]
What is proven to work on a plain Ubuntu 22.04 system (just did it myself last week):
```shell
$ sudo apt install iraf xgterm
$ xgterm -e irafcl &
```
and in the xgterm:
```
ecl> implot dev$pix
```
and it shows the graphics window.

**Comment by crabcakies231** [comment]
those are not the instructions given in the quoted gihub page, which i
followed.

**Comment by olebole** [comment]
That is the easiest way to get IRAF working on Ubuntu. And, actually, it says:

IRAF installation:
 > On some systems (Ubuntu, Debian, Mint, Mageia), IRAF can be directly installed from the package repositories.

X11IRAF:
> On some systems, x11iraf can be directly installed from the package repositories:
> * Ubuntu 19.10 “Eoan Ermine” and later,

which implies that both IRAF and x11iraf can be installed with the normal package manager. And the startup of xgterm and IRAF didn't change since ages (except, that Debian uses **irafcl** instead of **ecl** to avoid conflicts with the Common Lisp compiler).
You can also just start xgterm and within the xgterm window start **irafcl** (or **ecl** if you have a self-compiled system).

How exactly did you start it? And which IRAF did you use? And what exactly is the error message?

**Comment by crabcakies231** [comment]
yes, indeed that version of startup works.  but starting xgterm, the iraf
therewithin and then implot does not work, as demonstrated.

**Comment by crabcakies231** [comment]
thanks.  however it is now started.  i am back in business.

**Comment by olebole** [comment]
If you have further poblems, please use [IRAF discussions](https://github.com/orgs/iraf-community/discussions) instead of opening an issue.
