### ISSUE TITLE
Makefile issues

### ISSUE THREAD

**Issue by joezepeda** [iraf-community/x11iraf#6]
When running the command `make World` I received a fatal error. The error was because it couldn't find the file "X11/Xaw/XawInit.h". After tracking down the location of XawInit.h in "x11/iraf/include/X11/Xaw3d/", I resolved this by `mkdir Xaw` when in the X11 directory. Then I copied the contents of "Xaw3d" into "Xaw" with the command `cp Xaw3d/* Xaw/`. `make World` ran successfully after this and I found the executable in "x11iraf/bin".

So If anyone else runs into this problem this should solve it.

This is a minor issue, but it did give me some trouble to find the fix. If this could be addressed in an update I know it would be appreciated by beginner iraf users like myself :)

**Comment by joezepeda** [comment]
Note: my fix requires you to run `make World` and get the fatal error before you can rename the directory. The unsuccessful "make World" command moves files and makes new directories so you want to run it before you do the steps to resolve it as I did above.

**Comment by olebole** [comment]
I think this should be resolved with #19
